# Generated by Django 4.2.14 on 2024-07-31 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeaffectation', models.IntegerField()),
                ('intituler', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GrpsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(choices=[('ADMIN', 'admin'), ('UTILISATEUR', 'utilisateur')], max_length=30, null=True)),
                ('descriptiongrps', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('is_admin', models.BooleanField(default=False)),
                ('codeaffectation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.affectation')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('MATERIEL', 'materiel'), ('LOGICIEL', 'logiciel')], default='MATERIEL', max_length=30)),
                ('selection', models.CharField(max_length=30)),
                ('date_of_Add', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('NOUVEAU', 'nouveau'), ('EN INSTANCE', 'en instance'), ('EN COURS DE TRAITEMENT', 'en cours de traitement'), ('TRAITER', 'traiter'), ('CLOTURE', 'cloture')], default='NOUVEAU', max_length=30)),
                ('response', models.TextField(blank=True, null=True)),
                ('date_de_changement', models.DateField(default=datetime.date.today, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Hbilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=50)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.grpsuser')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.user_info')),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
    ]
